# This is a basic workflow to help you get started with Actions

name: deliveryGift

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule: 
       - cron: '8 4 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  start:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2

      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests
      # Runs a set of commands using the runners shell
      - name: 'Get points'
        env:
          BILI_JCT: ${{ secrets.BILI_JCT }}
          SESSDATA: ${{ secrets.SESSDATA }}
          DEDEUSERID: ${{ secrets.DEDEUSERID }}
        run: python live.py
